apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-classifier-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: jkmohite/email-classifier-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_CLIENT_ID
              value: your_google_client_id
            - name: GOOGLE_CLIENT_SECRET
              value: your_google_client_secret
