apiVersion: v1
kind: Service
metadata:
  name: email-classifier-backend-np-service
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007 # This port can be any valid port within the NodePort range
  type: NodePort
